# -*- coding: utf-8 -*-
"""Common.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/12T3WIi8_PRjdC2989hdyO91KH619h1x8
"""

import math

class Crime:
  def __init__(self, id, lat, long, type, date):
    self.id = id
    self.lat = lat
    self.long = long
    self.type = type
    self.date = date
  def __str__(self):
    return "Date:{} ID:{} Lat:{} Long:{} Type:{}".format(self.date, self.id, self.lat, self.long, self.type)
  def to_dict(self):
        return {
            "Date": self.date,
            "ID": self.id,
            "Lat": self.lat,
            "Long": self.long,
            "Type": self.type,
        }

def OffsetCoordinate(lat, lon, dx, dy):
  r_earth = 6378

  new_latitude  = lat  + (dy / r_earth) * (180 / math.pi);
  new_longitude = lon + (dx / r_earth) * (180 / math.pi) / math.cos(lat * math.pi/180);
  return new_latitude, new_longitude